#    _          _   _         _       _           _
#   / \   _ __ | |_(_)       / \   __| |_ __ ___ (_)_ __
#  / _ \ | '_ \| __| |_____ / _ \ / _` | '_ ` _ \| | '_ \
# / ___ \| | | | |_| |_____/ ___ \ (_| | | | | | | | | | |
#/_/   \_\_| |_|\__|_|    /_/   \_\__,_|_| |_| |_|_|_| |_|

# Developed by Mitlit & rizz

#Spigot: https://www.spigotmc.org/resources/anti-admin.108054/
#Github: https://github.com/ThatAlbaPerson/AntiAdmin
#Patreon: https://www.patreon.com/mitlit
#Font: https://patorjk.com/software/taag/#p=display&h=1&v=1&f=Standard&t=Prefixes



#__        __   _     _                 _
#\ \      / /__| |__ | |__   ___   ___ | | _____
#\ \ /\ / / _ \ '_ \| '_ \ / _ \ / _ \| |/ / __|
#\ V  V /  __/ |_) | | | | (_) | (_) |   <\__ \
#\_/\_/ \___|_.__/|_| |_|\___/ \___/|_|\_\___/

#Discord Webhook -  This is where the discord notification is sent (Not Required)
discord_webhook_url: ""
#Use Embeds - Set it to true if you want it to send embeds, Set it to false if you just want plain text.
use_embeds: true

#____            __ _
#|  _ \ _ __ ___ / _(_)_  _____  ___
#| |_) | '__/ _ \ |_| \ \/ / _ \/ __|
#|  __/| | |  __/  _| |>  <  __/\__ \
# |_|   |_|  \___|_| |_/_/\_\___||___/

#The "plugin_prefix" is the prefix displayed in SERVER MESSAGES, If you wish for this to NOT be visible just remove the message and leave the string blank.
plugin_prefix: "&4&l[&r&cAntiAdmin&4&l]&r"
# With the "discord_prefix" you are UNABLE to use MC color codes, as this goes directly to the discord webhook.
discord_prefix: ""



# _____             _
#|  ___|___   __ _ | |_  _   _  _ __  ___  ___
#| |_  / _ \ / _` || __|| | | || '__|/ _ \/ __|
#|  _||  __/| (_| || |_ | |_| || |  |  __/\__ \
#|_|   \___| \__,_| \__| \__,_||_|   \___||___/

#Allows players to run the command "/antiadmin list-ops" where it will list all server operators
enable_op_list: true



#    _                                                                _
#   / \   _ __  _ __   ___  _   _ _ __   ___ ___ _ __ ___   ___ _ __ | |_ ___
#  / _ \ | '_ \| '_ \ / _ \| | | | '_ \ / __/ _ \ '_ ` _ \ / _ \ '_ \| __/ __|
# / ___ \| | | | | | | (_) | |_| | | | | (_|  __/ | | | | |  __/ | | | |_\__ \
#/_/   \_\_| |_|_| |_|\___/ \__,_|_| |_|\___\___|_| |_| |_|\___|_| |_|\__|___/

#Alert Sound - Plays a sound for all players when an admin uses a "blocked" command
play_sound: true



#   ___         _                            _    _
#  |_ _| _ __  | |_  ___   __ _  _ __  __ _ | |_ (_)  ___   _ __   ___
#  | | | '_ \ | __|/ _ \ / _` || '__|/ _` || __|| | / _ \ | '_ \ / __|
#  | | | | | || |_|  __/| (_| || |  | (_| || |_ | || (_) || | | |\__ \
# |___||_| |_| \__|\___| \__, ||_|   \__,_| \__||_| \___/ |_| |_||___/
#                        |___/

#Enables the LuckPerms integration
luckperms: true
